import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { renderSprintOverview } from '../public/sprint-overview.js';
const kpis=metrics=>`<div class="kpis">${Object.entries(metrics).map(([key,value])=>`<button data-briefing-detail="${key}">${value}</button>`).join('')}</div>`;
const data={projects:[{name:'A',notionId:'a',currentSprints:['Sprint3'],sprintRequired:true,specs:[]}],workItems:[{id:'x',project:'A',sprint:'Sprint4',status:'진행 중',title:'Test'}],sprintSettings:{writable:true,projects:{},history:[]}};
const state={selections:{},filters:{},detail:null,message:'',expanded:true,saving:false};
test('Section uses checkboxes for multi-selection',()=>{const html=renderSprintOverview(data,state,kpis);assert.ok(html.includes('3. 스프린트별 업무 현황'));assert.equal((html.match(/type="checkbox"/g)||[]).length,2);assert.ok(html.includes('복수 선택'));});
test('Preview is explicitly separate from saved AI analysis',()=>{const html=renderSprintOverview(data,{...state,selections:{a:['Sprint4']}},kpis);assert.ok(html.includes('조회 미리보기'));assert.ok(html.includes('AI 분석이 다시 실행되지는 않습니다'));});
test('Disable save without server administrator capability',()=>assert.ok(renderSprintOverview({...data,sprintSettings:{writable:false}},state,kpis).includes('data-scope-save="a" disabled')));
test('Untrusted project and sprint values are escaped',()=>{const html=renderSprintOverview({...data,projects:[{...data.projects[0],name:'<img src=x onerror=alert(1)>'}]},state,kpis);assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;img'));});
test('Admin key is masked and never persisted',()=>{const code=fs.readFileSync(new URL('../public/sprint-overview.js',import.meta.url),'utf8');assert.ok(code.includes('type="password"'));assert.doesNotMatch(code,/localStorage|sessionStorage/);});
test('All metrics grouped after analysis and changes',()=>{const code=fs.readFileSync(new URL('../public/dashboard-presenters.js',import.meta.url),'utf8');const a=code.lastIndexOf('1. 에이전트 통합 분석'),b=code.lastIndexOf('2. 어제와 달라진 것'),c=code.lastIndexOf('${sprintOverviewHtml');assert.ok(a>=0&&a<b&&b<c);});
test('Backend connects shared settings without changing raw metrics',()=>{const api=fs.readFileSync(new URL('../api/app.mjs',import.meta.url),'utf8'),collect=fs.readFileSync(new URL('../collect.mjs',import.meta.url),'utf8');assert.ok(api.includes('settingsWriteAuthorized'));assert.ok(api.includes('settingsOriginAllowed'));assert.ok(collect.includes('applySavedSprintSettings'));assert.ok(collect.includes('agentInput.rules.briefingMetrics = workOverview.metrics'));assert.ok(!collect.includes('agentInput.rules.metrics = workOverview.metrics'));});
