import test from 'node:test';
import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { readSprintSettings,saveSprintSettings,settingsWriteAuthorized,settingsOriginAllowed,readSettingsBody,decorateSprintDashboard,applySavedSprintSettings } from '../lib/sprint-settings.mjs';
import { scopeSignature } from '../public/sprint-policy.js';
function storage(){const pages=[];return {pages,query:async()=>pages,create:async(db,properties)=>{pages.push({id:`p${pages.length}`,properties});return pages.at(-1);}};}
function dashboard(){return {projects:[{name:'A',notionId:'a',currentSprints:['Sprint3'],sprintRequired:true,specs:[]}],workItems:[{id:'x',project:'A',sprint:'Sprint4',status:'진행 중'}],ai:{analysisStatus:'success',generatedAt:'2026-09-07T10:00:00+09:00'},sourceHealth:{status:'ok',sources:[{id:'agent-analysis',status:'ok',analysisStatus:'success'}]}};}
test('First save is append-only, persistent and read back',async()=>{const s=storage();const r=await saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:['Sprint3','Sprint4'],expectedRevision:null,...s,uuid:()=> 'r1'});assert.equal(s.pages.length,1);assert.deepEqual(r.settings.projects.a.sprints,['Sprint3','Sprint4']);assert.equal((await readSprintSettings({databaseId:'db',query:s.query})).projects.a.revision,'r1');});
test('Stale editor gets conflict without another write',async()=>{const s=storage();await saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:['Sprint4'],expectedRevision:null,...s,uuid:()=> 'r1'});await assert.rejects(()=>saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:['Sprint3'],expectedRevision:null,...s}),e=>e.statusCode===409);assert.equal(s.pages.length,1);});
test('Empty saved selection never falls back to Notion',async()=>{const s=storage();const {settings}=await saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:[],expectedRevision:null,...s,uuid:()=> 'r1'});const p=applySavedSprintSettings(dashboard().projects,settings);assert.deepEqual(p[0].currentSprints,[]);assert.equal(p[0].sprintSettingSource,'dashboard');});
test('History retains previous sprint choice',async()=>{const s=storage();await saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:['Sprint4'],expectedRevision:null,now:'2026-09-07T10:00:00Z',...s,uuid:()=> 'r1'});const {settings}=await saveSprintSettings({databaseId:'db',dashboard:dashboard(),projectId:'a',sprints:['Sprint3'],expectedRevision:'r1',now:'2026-09-07T10:01:00Z',...s,uuid:()=> 'r2'});assert.equal(s.pages.length,2);assert.equal(settings.projects.a.revision,'r2');assert.deepEqual(settings.history[0].previousSprints,['Sprint4']);});
test('Reject unknown sprint or project',async()=>{const s=storage();for(const v of [{projectId:'a',sprints:['Sprint999']},{projectId:'unknown',sprints:['Sprint3']}])await assert.rejects(()=>saveSprintSettings({databaseId:'db',dashboard:dashboard(),expectedRevision:null,...s,...v}),e=>e.statusCode===400);assert.equal(s.pages.length,0);});
test('Legacy snapshot cannot save an unstable project name key',async()=>{const d=dashboard();delete d.projects[0].notionId;await assert.rejects(()=>saveSprintSettings({databaseId:'db',dashboard:d,projectId:'A',sprints:[],expectedRevision:null,...storage()}),e=>e.statusCode===409);});
test('Malformed configuration fails rather than silently reverting',async()=>{await assert.rejects(()=>readSprintSettings({query:async()=>{throw Error('network');}}));await assert.rejects(()=>readSprintSettings({query:async()=>[{properties:{payload:{rich_text:[{text:{content:'broken'}}]}}}]}),e=>e.statusCode===503);});
test('Write requires a separate strong administrator token',()=>{const token='a'.repeat(32);assert.equal(settingsWriteAuthorized({headers:{}},token),false);assert.equal(settingsWriteAuthorized({headers:{authorization:'Bearer wrong'}},token),false);assert.equal(settingsWriteAuthorized({headers:{authorization:`Bearer ${token}`}},token),true);assert.equal(settingsWriteAuthorized({headers:{authorization:'Bearer tiny'}},'tiny'),false);});
test('Reject cross-origin browser settings writes',()=>{assert.equal(settingsOriginAllowed({headers:{origin:'https://evil.example',host:'dashboard.example'}}),false);assert.equal(settingsOriginAllowed({headers:{origin:'https://dashboard.example',host:'dashboard.example'}}),true);});
test('Limit parsed and streamed request bodies',async()=>{await assert.rejects(()=>readSettingsBody({body:{x:'x'.repeat(17000)}}),e=>e.statusCode===413);await assert.rejects(()=>readSettingsBody(Readable.from(['x'.repeat(17000)])),e=>e.statusCode===413);assert.deepEqual(await readSettingsBody({body:'{"a":1}'}),{a:1});});
test('Scope changes invalidate analysis and trust together',()=>{const d=dashboard();d.sprintScope={signature:scopeSignature(d.projects)};const settings={revision:'r',history:[],projects:{a:{sprints:['Sprint4'],revision:'r'}}};const v=decorateSprintDashboard(d,settings);assert.equal(v.ai.analysisStatus,'stale');assert.equal(v.sourceHealth.sources[0].analysisStatus,'stale');assert.equal(v.sprintSettings.pendingInput,true);assert.equal(d.ai.analysisStatus,'success');});
test('Equivalent scope does not unnecessarily invalidate analysis',()=>{const r=decorateSprintDashboard(dashboard(),{revision:'r',history:[],projects:{a:{sprints:['스프린트3'],revision:'r'}}});assert.equal(r.sprintSettings.pendingInput,false);assert.equal(r.ai.analysisStatus,'success');});

test('Fresh collection does not relabel an older same-day analysis as current', () => {
  const dashboard = { projects: [], generatedAt: '2026-09-07T04:00:00Z', agentHandoff: {generatedAt: '2026-09-07T04:00:00Z'}, ai: {analysisStatus: 'success', generatedAt: '2026-09-07T00:00:00Z'} };
  const output = decorateSprintDashboard(dashboard, {projects:{},revision:'r',history:[]});
  assert.equal(output.sprintSettings.pendingInput, false);
  assert.equal(output.sprintSettings.pendingAnalysis, true);
  assert.equal(output.ai.analysisStatus, 'stale');
});
