import test from 'node:test';
import assert from 'node:assert/strict';
import { buildSprintOverview, classifySprint, normalizeSprint, uniqueSprints, scopeSignature, applySprintSelections, sortIssuesOverdueFirst } from '../public/sprint-policy.js';
const guide={type:'MISSING_BRANCH',category:'guide',severity:'error'};
const overdue={type:'OVERDUE',category:'schedule',severity:'warning'};
function fixture(){
 const projects=[{name:'A',notionId:'a',currentSprints:['Sprint3'],sprintRequired:true,specs:[]},{name:'B',notionId:'b',currentSprints:['Sprint8'],sprintRequired:true,specs:[]},{name:'Ops',notionId:'o',sprintRequired:false,specs:[]}];
 const task=(id,project,sprint,status,issues=[])=>({id,title:id,project,sprint,status,itemLevel:'child',issues,assignees:['Owner'],team:'개발'});
 const workItems=[task('a3','A','스프린트3','진행 중'),task('a4','A','Sprint 4','진행 중',[guide]),task('a3-late','A','Sprint3','진행 중',[overdue,guide]),task('a3-ready','A','Sprint3','시작 전'),task('a2-late','A','Sprint2','진행 중',[overdue,guide]),task('a-none','A',null,'진행 중',[guide]),task('b8','B','Sprint8','진행 중',[guide]),task('b3','B','Sprint3','진행 중',[guide]),task('ops','Ops',null,'진행 중',[guide]),task('ops-ready','Ops',null,'시작 전'),task('closed','A','Sprint3','완료',[overdue]),task('pause','A','Sprint3','일시 정지',[guide])];
 return {projects,workItems,validationIssues:[],metrics:{guideViolationWorkItems:91}};
}
test('Equivalent labels normalize and deduplicate',()=>{assert.equal(normalizeSprint(' 스프린트 003 '),'sprint3');assert.equal(uniqueSprints(['Sprint3','스프린트3','Sprint4']).length,2);});
for(const [value,selected,expected] of [['Sprint3',['Sprint3','Sprint5'],'current'],['Sprint5',['Sprint3','Sprint5'],'current'],['Sprint4',['Sprint3','Sprint5'],'unknown'],['Sprint2',['Sprint3','Sprint5'],'past'],['Sprint6',['Sprint3','Sprint5'],'future'],['Sprint3',[],'unknown'],[null,['Sprint3'],'unknown']]) test(`Relation ${value}/${selected}->${expected}`,()=>assert.equal(classifySprint(value,selected),expected));
test('Five metrics share selected scope and child-only unit',()=>assert.deepEqual(buildSprintOverview(fixture()).metrics,{activeProjects:3,inProgressWorkItems:4,overdueWorkItems:1,guideViolationWorkItems:2,progressSetupRequiredItems:1}));
test('Multiple selections are OR and project-specific',()=>{const v=buildSprintOverview(fixture(),{a:['Sprint3','Sprint4']});assert.ok(v.workItems.some(i=>i.id==='a4'));assert.ok(!v.workItems.some(i=>i.id==='b3'));assert.equal(v.metrics.guideViolationWorkItems,3);});
test('Empty is not ALL; other project scopes stay intact',()=>{const v=buildSprintOverview(fixture(),{a:[]});assert.equal(v.workItems.filter(i=>i.project==='A').length,0);assert.ok(v.workItems.some(i=>i.project==='B'));assert.ok(v.unconfiguredProjects.includes('A'));});
test('Overdue wins while raw data and counts remain immutable',()=>{const d=fixture();const original=JSON.stringify(d);const v=buildSprintOverview(d);assert.ok(v.overdueItems.some(i=>i.id==='a3-late'));assert.ok(!v.guideViolationItems.some(i=>i.id==='a3-late'));assert.equal(v.overdueItems[0].issues.length,2);assert.equal(JSON.stringify(d),original);});
test('Guide count counts tasks rather than failed rules',()=>{const d=fixture();d.workItems.find(i=>i.id==='b8').issues.push({...guide,type:'MISSING_PRIORITY'});assert.equal(buildSprintOverview(d).metrics.guideViolationWorkItems,2);});
test('Outside overdue and missing sprint remain discoverable',()=>{const v=buildSprintOverview(fixture());assert.deepEqual(v.outsideOverdueItems.map(i=>i.id),['a2-late']);assert.ok(v.unknownSprintItems.some(i=>i.id==='a-none'));});
test('No-sprint project is active but not sprint preparation',()=>{const v=buildSprintOverview(fixture());assert.ok(v.workItems.some(i=>i.id==='ops-ready'));assert.ok(!v.progressSetupItems.some(i=>i.id==='ops-ready'));});
test('Closed tasks and children of closed parents are excluded',()=>{const d=fixture();d.projects[0].specs.push({id:'closed-parent',status:'중단'});d.workItems.push({id:'hidden-child',project:'A',sprint:'Sprint3',status:'진행 중',specId:'closed-parent'});assert.ok(!buildSprintOverview(d).workItems.some(i=>['closed','pause','hidden-child'].includes(i.id)));});
test('Parent issues do not inflate child task KPIs',()=>{const d=fixture();d.workItems.push({id:'parent',itemLevel:'parent',project:'A',sprint:'Sprint3',status:'진행 중',issues:[guide]});assert.equal(buildSprintOverview(d).metrics.guideViolationWorkItems,2);});
test('Compact snapshot issue links are restored',()=>{const d=fixture();d.workItems.find(i=>i.id==='b8').issues=[];d.validationIssues=[{...guide,workItemId:'b8'}];assert.equal(buildSprintOverview(d).metrics.guideViolationWorkItems,2);});
test('Filters affect lists and counters consistently',()=>{const v=buildSprintOverview(fixture(),{},{project:'A'});assert.equal(v.metrics.activeProjects,1);assert.equal(v.metrics.inProgressWorkItems,2);assert.equal(v.metrics.inProgressWorkItems,v.runningItems.length);assert.equal(v.metrics.guideViolationWorkItems,v.guideViolationItems.length);});
test('Scope identity ignores order and equivalent spelling',()=>{const d=fixture();assert.equal(scopeSignature(applySprintSelections(d.projects,{a:['Sprint4','스프린트3']})),scopeSignature(applySprintSelections(d.projects,{a:['Sprint3','Sprint 4']})));});
test('Overdue issue is primary despite guide error severity',()=>assert.equal(sortIssuesOverdueFirst([guide,overdue])[0].type,'OVERDUE'));
test('No tasks has zero counts without invented scope',()=>assert.deepEqual(Object.values(buildSprintOverview({projects:[],workItems:[]}).metrics),[0,0,0,0,0]));
