import core1 from './core-001.mjs';
import core2 from './core-002.mjs';
import core3 from './core-003.mjs';
import core4 from './core-004.mjs';
import core5 from './core-005.mjs';
import core6 from './core-006.mjs';
import core7 from './core-007.mjs';
import core8 from './core-008.mjs';
import core9 from './core-009.mjs';
import core10 from './core-010.mjs';
import core11 from './core-011.mjs';
import core12 from './core-012.mjs';
import core13 from './core-013.mjs';
import core14 from './core-014.mjs';
import core15 from './core-015.mjs';
import core16 from './core-016.mjs';
import core17 from './core-017.mjs';
import core18 from './core-018.mjs';
import asset1 from './assets-001.mjs';
import asset2 from './assets-002.mjs';
import asset3 from './assets-003.mjs';
import asset4 from './assets-004.mjs';
import asset5 from './assets-005.mjs';
import asset6 from './assets-006.mjs';
import asset7 from './assets-007.mjs';
import asset8 from './assets-008.mjs';
import asset9 from './assets-009.mjs';
import asset10 from './assets-010.mjs';
import asset11 from './assets-011.mjs';
import asset12 from './assets-012.mjs';
import asset13 from './assets-013.mjs';
import asset14 from './assets-014.mjs';
import asset15 from './assets-015.mjs';
import asset16 from './assets-016.mjs';
import asset17 from './assets-017.mjs';
import asset18 from './assets-018.mjs';
import asset19 from './assets-019.mjs';
import asset20 from './assets-020.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { gunzipSync } from 'node:zlib';
const root=process.cwd();
const assetJson=gunzipSync(Buffer.from([asset1,asset2,asset3,asset4,asset5,asset6,asset7,asset8,asset9,asset10,asset11,asset12,asset13,asset14,asset15,asset16,asset17,asset18,asset19,asset20].join(''),'base64')).toString('utf8');
const assetSource=JSON.parse(assetJson);
const virtual=new Map();
for(const [name,value] of Object.entries(assetSource)){const buffer=Buffer.from(value,'utf8');virtual.set(path.resolve(root,name),buffer);virtual.set(path.resolve('/',name),buffer);}
const keyFor=(target)=>{if(target instanceof URL)return fileURLToPath(target);const text=String(target);if(text.startsWith('file:'))return fileURLToPath(text);return path.resolve(text);};
const originalRead=fs.readFileSync.bind(fs);
const originalExists=fs.existsSync.bind(fs);
const originalStat=fs.statSync.bind(fs);
fs.existsSync=(target)=>virtual.has(keyFor(target))||originalExists(target);
fs.readFileSync=(target,options)=>{const value=virtual.get(keyFor(target));if(!value)return originalRead(target,options);const enc=typeof options==='string'?options:options?.encoding;return enc?value.toString(enc):Buffer.from(value);};
fs.statSync=(target,...args)=>{const value=virtual.get(keyFor(target));if(!value)return originalStat(target,...args);return {size:value.length,isFile:()=>true,isDirectory:()=>false};};
let corePromise;
async function loadCore(){if(!corePromise){const source=gunzipSync(Buffer.from([core1,core2,core3,core4,core5,core6,core7,core8,core9,core10,core11,core12,core13,core14,core15,core16,core17,core18].join(''),'base64'));const corePath=path.join('/tmp','molip-dashboard-core-5c7fff.mjs');fs.writeFileSync(corePath,source);corePromise=import(pathToFileURL(corePath).href);}return corePromise;}
export default async function handler(request,response){const mod=await loadCore();return mod.default(request,response);}
